name: Build & Deploy to GKE

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - ".github/workflows/build-and-deploy.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # Needed for Workload Identity Federation

env:
  PROJECT_ID: gcp-learning-tut
  REGION: us-central1
  ARTIFACT_REPO: expense-tracker
  IMAGE_NAME: backend
  REGISTRY: us-central1-docker.pkg.dev

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.vars.outputs.sha_tag }}
      image_uri: ${{ steps.vars.outputs.image_uri }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_REGISTRY_IMAGE_PUSH }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker $REGISTRY --quiet

      - name: Define image tag and uri
        id: vars
        run: |
          TAG=${GITHUB_SHA::7}
          IMAGE_URI=${REGISTRY}/${PROJECT_ID}/${ARTIFACT_REPO}/${IMAGE_NAME}
          echo "sha_tag=$TAG" >> $GITHUB_OUTPUT
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          provenance: false
          tags: |
            ${{ steps.vars.outputs.image_uri }}:${{ steps.vars.outputs.sha_tag }}
            ${{ steps.vars.outputs.image_uri }}:latest
          cache-from: type=registry,ref=${{ steps.vars.outputs.image_uri }}:buildcache
          cache-to: type=registry,ref=${{ steps.vars.outputs.image_uri }}:buildcache,mode=max


