name: Build & push frontened image

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - ".github/workflows/build-and-deploy.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # Needed for Workload Identity Federation

env:
  PROJECT_ID: gcp-learning-tut
  REGION: us-central1
  ARTIFACT_REPO: expense-tracker
  IMAGE_NAME: frontened
  REGISTRY: us-central1-docker.pkg.dev

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.vars.outputs.sha_tag }}
      image_uri: ${{ steps.vars.outputs.image_uri }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with GCP using key file
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_REGISTRY_IMAGE_PUSH }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker $REGISTRY --quiet

      - name: Define image tag and uri
        id: vars
        run: |
          TAG=${GITHUB_SHA::7}
          IMAGE_URI=${REGISTRY}/${PROJECT_ID}/${ARTIFACT_REPO}/${IMAGE_NAME}
          echo "sha_tag=$TAG" >> $GITHUB_OUTPUT
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: create docker images
        run: |
          docker build -t  ${{ steps.vars.outputs.image_uri }}:${{ steps.vars.outputs.sha_tag }} -f frontened/Dockerfile .
          docker images

      - name: push docker images to registry
        run: |
          docker push  ${{ steps.vars.outputs.image_uri }}:${{ steps.vars.outputs.sha_tag }}



